// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SaveDataRequest struct {
	Data                 *Data    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveDataRequest) Reset()         { *m = SaveDataRequest{} }
func (m *SaveDataRequest) String() string { return proto.CompactTextString(m) }
func (*SaveDataRequest) ProtoMessage()    {}
func (*SaveDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *SaveDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveDataRequest.Unmarshal(m, b)
}
func (m *SaveDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveDataRequest.Marshal(b, m, deterministic)
}
func (m *SaveDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveDataRequest.Merge(m, src)
}
func (m *SaveDataRequest) XXX_Size() int {
	return xxx_messageInfo_SaveDataRequest.Size(m)
}
func (m *SaveDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveDataRequest proto.InternalMessageInfo

func (m *SaveDataRequest) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type SaveDataResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveDataResponse) Reset()         { *m = SaveDataResponse{} }
func (m *SaveDataResponse) String() string { return proto.CompactTextString(m) }
func (*SaveDataResponse) ProtoMessage()    {}
func (*SaveDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *SaveDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveDataResponse.Unmarshal(m, b)
}
func (m *SaveDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveDataResponse.Marshal(b, m, deterministic)
}
func (m *SaveDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveDataResponse.Merge(m, src)
}
func (m *SaveDataResponse) XXX_Size() int {
	return xxx_messageInfo_SaveDataResponse.Size(m)
}
func (m *SaveDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveDataResponse proto.InternalMessageInfo

func (m *SaveDataResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *SaveDataResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetDataRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataRequest) Reset()         { *m = GetDataRequest{} }
func (m *GetDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetDataRequest) ProtoMessage()    {}
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *GetDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataRequest.Unmarshal(m, b)
}
func (m *GetDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataRequest.Marshal(b, m, deterministic)
}
func (m *GetDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataRequest.Merge(m, src)
}
func (m *GetDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetDataRequest.Size(m)
}
func (m *GetDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataRequest proto.InternalMessageInfo

func (m *GetDataRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetDataResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *Data    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataResponse) Reset()         { *m = GetDataResponse{} }
func (m *GetDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetDataResponse) ProtoMessage()    {}
func (*GetDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *GetDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataResponse.Unmarshal(m, b)
}
func (m *GetDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataResponse.Marshal(b, m, deterministic)
}
func (m *GetDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataResponse.Merge(m, src)
}
func (m *GetDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetDataResponse.Size(m)
}
func (m *GetDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataResponse proto.InternalMessageInfo

func (m *GetDataResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *GetDataResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetDataResponse) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type Data struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data                 [][]byte `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Data) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Data) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*SaveDataRequest)(nil), "proto.SaveDataRequest")
	proto.RegisterType((*SaveDataResponse)(nil), "proto.SaveDataResponse")
	proto.RegisterType((*GetDataRequest)(nil), "proto.GetDataRequest")
	proto.RegisterType((*GetDataResponse)(nil), "proto.GetDataResponse")
	proto.RegisterType((*Data)(nil), "proto.Data")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x46, 0x5c, 0xfc, 0xc1,
	0x89, 0x65, 0xa9, 0x2e, 0x89, 0x25, 0x89, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0xf2,
	0x5c, 0x2c, 0x29, 0x89, 0x25, 0x89, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0xdc, 0x10, 0xf5,
	0x7a, 0x60, 0x15, 0x60, 0x09, 0x25, 0x1b, 0x2e, 0x01, 0x84, 0x9e, 0xe2, 0x82, 0xfc, 0xbc, 0xe2,
	0x54, 0x21, 0x3e, 0x2e, 0xa6, 0xfc, 0x6c, 0xb0, 0x16, 0x8e, 0x20, 0xa6, 0xfc, 0x6c, 0x21, 0x09,
	0x2e, 0xf6, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20,
	0x18, 0x57, 0x49, 0x89, 0x8b, 0xcf, 0x3d, 0xb5, 0x04, 0xd9, 0x42, 0x01, 0x2e, 0xe6, 0xec, 0xd4,
	0x4a, 0xb0, 0x66, 0xce, 0x20, 0x10, 0x53, 0x29, 0x86, 0x8b, 0x1f, 0xae, 0x86, 0x54, 0x0b, 0xe0,
	0xee, 0x67, 0xc6, 0xe5, 0x7e, 0x2f, 0x2e, 0x16, 0x10, 0x0f, 0xd3, 0x5e, 0x21, 0x21, 0xa8, 0x56,
	0x26, 0x05, 0x66, 0x0d, 0x1e, 0x88, 0x6a, 0x21, 0x19, 0x2e, 0xce, 0x92, 0xcc, 0xdc, 0xd4, 0xe2,
	0x92, 0xc4, 0xdc, 0x02, 0xb0, 0x99, 0xcc, 0x41, 0x08, 0x81, 0x24, 0x36, 0xb0, 0xe9, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x3b, 0x9f, 0x82, 0x5c, 0x01, 0x00, 0x00,
}
