// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SaveDataRequest struct {
	Data                 *Data    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveDataRequest) Reset()         { *m = SaveDataRequest{} }
func (m *SaveDataRequest) String() string { return proto.CompactTextString(m) }
func (*SaveDataRequest) ProtoMessage()    {}
func (*SaveDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *SaveDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveDataRequest.Unmarshal(m, b)
}
func (m *SaveDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveDataRequest.Marshal(b, m, deterministic)
}
func (m *SaveDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveDataRequest.Merge(m, src)
}
func (m *SaveDataRequest) XXX_Size() int {
	return xxx_messageInfo_SaveDataRequest.Size(m)
}
func (m *SaveDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveDataRequest proto.InternalMessageInfo

func (m *SaveDataRequest) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type SaveDataResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveDataResponse) Reset()         { *m = SaveDataResponse{} }
func (m *SaveDataResponse) String() string { return proto.CompactTextString(m) }
func (*SaveDataResponse) ProtoMessage()    {}
func (*SaveDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *SaveDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveDataResponse.Unmarshal(m, b)
}
func (m *SaveDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveDataResponse.Marshal(b, m, deterministic)
}
func (m *SaveDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveDataResponse.Merge(m, src)
}
func (m *SaveDataResponse) XXX_Size() int {
	return xxx_messageInfo_SaveDataResponse.Size(m)
}
func (m *SaveDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveDataResponse proto.InternalMessageInfo

func (m *SaveDataResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *SaveDataResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetDataRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataRequest) Reset()         { *m = GetDataRequest{} }
func (m *GetDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetDataRequest) ProtoMessage()    {}
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *GetDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataRequest.Unmarshal(m, b)
}
func (m *GetDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataRequest.Marshal(b, m, deterministic)
}
func (m *GetDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataRequest.Merge(m, src)
}
func (m *GetDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetDataRequest.Size(m)
}
func (m *GetDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataRequest proto.InternalMessageInfo

func (m *GetDataRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetDataResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *Data    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataResponse) Reset()         { *m = GetDataResponse{} }
func (m *GetDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetDataResponse) ProtoMessage()    {}
func (*GetDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *GetDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataResponse.Unmarshal(m, b)
}
func (m *GetDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataResponse.Marshal(b, m, deterministic)
}
func (m *GetDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataResponse.Merge(m, src)
}
func (m *GetDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetDataResponse.Size(m)
}
func (m *GetDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataResponse proto.InternalMessageInfo

func (m *GetDataResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *GetDataResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetDataResponse) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type Data struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Data) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Data) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*SaveDataRequest)(nil), "proto.SaveDataRequest")
	proto.RegisterType((*SaveDataResponse)(nil), "proto.SaveDataResponse")
	proto.RegisterType((*GetDataRequest)(nil), "proto.GetDataRequest")
	proto.RegisterType((*GetDataResponse)(nil), "proto.GetDataResponse")
	proto.RegisterType((*Data)(nil), "proto.Data")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0xbf, 0x4b, 0x03, 0x31,
	0x14, 0x26, 0x77, 0xd5, 0xf6, 0x5e, 0xa4, 0x2d, 0x0f, 0xd4, 0xa3, 0x08, 0x96, 0x4c, 0x9d, 0x3a,
	0x9c, 0x8b, 0xa0, 0xa3, 0x20, 0x38, 0xa6, 0xab, 0x4b, 0xd4, 0x87, 0x94, 0xe3, 0x4c, 0x6c, 0x9e,
	0x85, 0xee, 0xfe, 0xe1, 0x92, 0x5c, 0xae, 0xd5, 0x16, 0x87, 0x4e, 0x77, 0xef, 0xcb, 0xf7, 0xeb,
	0x25, 0x20, 0x79, 0xe3, 0xc8, 0xcf, 0xdd, 0xca, 0xb2, 0xc5, 0x93, 0xf8, 0x51, 0x15, 0x8c, 0x16,
	0x66, 0x4d, 0x0f, 0x86, 0x8d, 0xa6, 0xcf, 0x2f, 0xf2, 0x8c, 0xd7, 0xd0, 0x7b, 0x33, 0x6c, 0x4a,
	0x31, 0x15, 0x33, 0x59, 0xc9, 0x96, 0x3f, 0x8f, 0x8c, 0x78, 0xa0, 0xee, 0x61, 0xbc, 0xd3, 0x78,
	0x67, 0x3f, 0x3c, 0xe1, 0x10, 0x32, 0x5b, 0x47, 0xc9, 0x40, 0x67, 0xb6, 0xc6, 0x12, 0xfa, 0x0d,
	0x79, 0x6f, 0xde, 0xa9, 0xcc, 0xa6, 0x62, 0x56, 0xe8, 0x6e, 0x54, 0x0a, 0x86, 0x8f, 0xc4, 0xbf,
	0x03, 0xc7, 0x90, 0xd7, 0xb4, 0x89, 0xe2, 0x42, 0x87, 0x5f, 0xf5, 0x0c, 0xa3, 0x2d, 0xe7, 0xd8,
	0x80, 0x6d, 0xff, 0xfc, 0xbf, 0xfe, 0x4f, 0xd0, 0x0b, 0xd3, 0x61, 0x2e, 0x62, 0x92, 0x06, 0xc7,
	0xb3, 0x96, 0x8d, 0x57, 0x50, 0xf0, 0xb2, 0x21, 0xcf, 0xa6, 0x71, 0xd1, 0x33, 0xd7, 0x3b, 0xa0,
	0xfa, 0x16, 0x20, 0x83, 0xd9, 0x82, 0x56, 0xeb, 0xe5, 0x2b, 0xe1, 0x2d, 0xf4, 0x53, 0x73, 0x3c,
	0x4f, 0xc9, 0x7f, 0xb7, 0x9d, 0x5c, 0xec, 0xc3, 0x69, 0xc1, 0x3b, 0x18, 0x74, 0xb7, 0x8a, 0x1d,
	0x67, 0xef, 0x69, 0x26, 0x97, 0x07, 0x78, 0x2b, 0x7e, 0x39, 0x8d, 0xf8, 0xcd, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xfe, 0xeb, 0x09, 0x43, 0xe3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataServiceClient interface {
	GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error)
	SaveData(ctx context.Context, in *SaveDataRequest, opts ...grpc.CallOption) (*SaveDataResponse, error)
}

type dataServiceClient struct {
	cc *grpc.ClientConn
}

func NewDataServiceClient(cc *grpc.ClientConn) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error) {
	out := new(GetDataResponse)
	err := c.cc.Invoke(ctx, "/proto.DataService/GetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) SaveData(ctx context.Context, in *SaveDataRequest, opts ...grpc.CallOption) (*SaveDataResponse, error) {
	out := new(SaveDataResponse)
	err := c.cc.Invoke(ctx, "/proto.DataService/SaveData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServiceServer is the server API for DataService service.
type DataServiceServer interface {
	GetData(context.Context, *GetDataRequest) (*GetDataResponse, error)
	SaveData(context.Context, *SaveDataRequest) (*SaveDataResponse, error)
}

// UnimplementedDataServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDataServiceServer struct {
}

func (*UnimplementedDataServiceServer) GetData(ctx context.Context, req *GetDataRequest) (*GetDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetData not implemented")
}
func (*UnimplementedDataServiceServer) SaveData(ctx context.Context, req *SaveDataRequest) (*SaveDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveData not implemented")
}

func RegisterDataServiceServer(s *grpc.Server, srv DataServiceServer) {
	s.RegisterService(&_DataService_serviceDesc, srv)
}

func _DataService_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DataService/GetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetData(ctx, req.(*GetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_SaveData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).SaveData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DataService/SaveData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).SaveData(ctx, req.(*SaveDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetData",
			Handler:    _DataService_GetData_Handler,
		},
		{
			MethodName: "SaveData",
			Handler:    _DataService_SaveData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types.proto",
}
